Repository mezzio/mezzio-session-cache, pull requests merged in 2022-09, with the labels that each got.

#30 Drop support for PHP 7.3, update laminas-coding-standard to ~2.4.0
  composer.json
  composer.lock
Labels: Enhancement, dependencies

#26 Adds an integration test for Session persistence
  .laminas-ci.json
  composer.json
  composer.lock
  psalm-baseline.xml
  test/Asset/TestHandler.php
  test/CacheSessionPersistenceFactoryTest.php
  test/CacheSessionPersistenceIntegrationTest.php
  test/CacheSessionPersistenceTest.php
  test/ConfigProviderTest.php
Labels: Documentation, Enhancement

#31 Apply PHP 7.4 syntax and typed property
  src/CacheSessionPersistence.php
  test/CacheSessionPersistenceTest.php
Labels: Enhancement
